version: '3.3'

services:
  ocr:
    container_name: ocr
    build: 
      context: .
      dockerfile: Dockerfile_gpu
      args:
        - BUILD_ARGS=-t paddle-ocr:gpu
    image: paddle-ocr:gpu
    ports:
      - "8091:8091"
    restart: always
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
